# Generated by Django 6.1.1 on 2026-09-03 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.airline')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.route')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('date_recorded', models.DateField()),
                ('min_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sample_count', models.PositiveIntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.airline')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.route')),
            ],
            options={
                'unique_together': {('airline', 'route', 'travel_date', 'date_recorded')},
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(blank=True, max_length=10)),
                ('travel_date', models.DateField()),
                ('departure_time', models.TimeField(null=True)),
                ('arrival_time', models.TimeField(null=True)),
                ('fare_class', models.CharField(default='economy', max_length=20)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('seats_available', models.PositiveSmallIntegerField(null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.URLField(blank=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.airline')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.route')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='pricing.scrapejob')),
            ],
            options={
                'indexes': [models.Index(fields=['airline', 'route', 'travel_date'], name='pricing_pri_airline_3acc61_idx'), models.Index(fields=['scraped_at'], name='pricing_pri_scraped_cf5e4d_idx')],
            },
        ),
    ]
